### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by dbz123123** [Massachute/VLF-LF-lightning-waveform-classification#1]
Excuse me,I have a few questions to ask:
1.What types of data were this model trained on (pictures or waveform sequence) ?
2. Can this model be open source (inorder to be used as a pretrained model) ?

LOOKING FORWARD TO HEARING FROM YOU SOON

**Comment by Massachute** [comment]
Glad for your feedbacks!
1) This model is trained on waveform sequences. The sequence format is as shown in test.csv.
2) This model will be open source with the&nbsp; waveform dataset in this year.&nbsp;
Please let me know if anything unclear.
Best wishes.



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 27, 2023 21:20 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Massachute/VLF-LF-lightning-waveform-classification] about model(Issue #1)




 
Excuse me,I have a few questions to ask:
 1.What types of data were this model trained on (pictures or waveform sequence) ?
 2. Can this model be open source (inorder to be used as a pretrained model) ?
 
LOOKING FORWARD TO HEARING FROM YOU SOON

**Comment by dbz123123** [comment]
Thank you for your answer, Good luck with the development of the model!
